# Generated by Django 5.2.9 on 2025-12-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_white_label_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizationrequest',
            name='frame_color',
            field=models.CharField(choices=[('black', 'Black'), ('dark_bronze', 'Dark Bronze'), ('stucco', 'Stucco'), ('white', 'White'), ('almond', 'Almond')], default='black', help_text='Selected frame color', max_length=20),
        ),
        migrations.AlterField(
            model_name='visualizationrequest',
            name='mesh_choice',
            field=models.CharField(choices=[('10x10_standard', '10x10 Standard'), ('12x12_standard', '12x12 Standard'), ('12x12_american', '12x12 American')], default='12x12_standard', help_text='Selected mesh type', max_length=20),
        ),
        migrations.AlterField(
            model_name='visualizationrequest',
            name='mesh_color',
            field=models.CharField(choices=[('black', 'Black (Recommended)'), ('stucco', 'Stucco'), ('bronze', 'Bronze')], default='black', help_text='Selected mesh color', max_length=20),
        ),
    ]
